### ISSUE TITLE
Add script for Sieve of Eratosthenes

### ISSUE THREAD

**Issue by vanguard07** [DipanshKhandelwal/PythonScripts#65]
- [x] Issue Title is in form `Add script for [insert name for script here]`
- [x] I have read the Contributing guidelines.
- [x] I have tested my script and ensure that it is working.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I ensure that I'm not assigned to more than 2 issues.
	- [x] Assign this issue to me (I want to work on this).

**Comment by DipanshKhandelwal** [comment]
fixed by #66
